services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ".:/src/app"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://backend:5000/healthz
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    depends_on:
      mongo:
        condition: service_healthy

  worker:
    build: .
    volumes:
      - ".:/src/app"
    command: celery -A make_celery.celery worker --loglevel INFO
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
