services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ".:/src/app"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://backend:5000/healthz
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=ads
      - DB_USERNAME=dev
      - DB_PASSWORD=dev
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/ads --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
