services:
  backend:
    build: .
    environment:
      SECRET_KEY: "dev"
      DATABASE_DSN: "host=postgres port=5432 dbname=ads user=ads password=ads"
    ports:
      - "5000:5000"
    volumes:
      - ".:/src/app"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://backend:5000/healthz
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    depends_on:
      postgres:
        condition: service_healthy

  worker:
    build: .
    environment:
      SECRET_KEY: "dev"
      DATABASE_DSN: "host=postgres port=5432 dbname=ads user=ads password=ads"
    volumes:
      - ".:/src/app"
    command: celery -A make_celery.celery worker --loglevel INFO
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "ads"
      POSTGRES_PASSWORD: "ads"
      POSTGRES_DB: "ads"
    healthcheck:
      test: pg_isready -U myuser -d db_prod
      interval: 10s
      timeout: 3s
      retries: 3
