services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ".:/src/app"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://backend:5000/healthz
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
